/* Generated By:JJTree&JavaCC: Do not edit this line. EG2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARA = 7;
  /** RegularExpression Id. */
  int SE = 8;
  /** RegularExpression Id. */
  int SENAO = 9;
  /** RegularExpression Id. */
  int RETORNO = 10;
  /** RegularExpression Id. */
  int INI = 11;
  /** RegularExpression Id. */
  int FUNCAO = 12;
  /** RegularExpression Id. */
  int MOSTRAR = 13;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 14;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 15;
  /** RegularExpression Id. */
  int ABRE_CHAVE = 16;
  /** RegularExpression Id. */
  int FECHA_CHAVE = 17;
  /** RegularExpression Id. */
  int VIRGULA = 18;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 19;
  /** RegularExpression Id. */
  int DELIMITAR_TEXTO = 20;
  /** RegularExpression Id. */
  int TIPO_INTEIRO = 21;
  /** RegularExpression Id. */
  int TIPO_REAL = 22;
  /** RegularExpression Id. */
  int TIPO_TEXTO = 23;
  /** RegularExpression Id. */
  int MAIOR = 24;
  /** RegularExpression Id. */
  int MENOR = 25;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 26;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int DIFERENTE = 29;
  /** RegularExpression Id. */
  int ATRIBUIR = 30;
  /** RegularExpression Id. */
  int MAIS = 31;
  /** RegularExpression Id. */
  int MENOS = 32;
  /** RegularExpression Id. */
  int MULT = 33;
  /** RegularExpression Id. */
  int DIVI = 34;
  /** RegularExpression Id. */
  int LETRA_MAIUSCULA = 35;
  /** RegularExpression Id. */
  int LETRA_MINUSCULA = 36;
  /** RegularExpression Id. */
  int NUMERO = 37;
  /** RegularExpression Id. */
  int DIGITO = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"para\"",
    "\"se\"",
    "\"!se\"",
    "\"retorno\"",
    "\"ini\"",
    "\"funcao\"",
    "\"mostrar\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"\\\'\"",
    "\"inteiro\"",
    "\"real\"",
    "\"texto\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<LETRA_MAIUSCULA>",
    "<LETRA_MINUSCULA>",
    "<NUMERO>",
    "<DIGITO>",
  };

}
