/* Generated By:JavaCC: Do not edit this line. EG2TreeConstants.java Version 5.0 */
public interface EG2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTMAIN = 1;
  public int JJTINI = 2;
  public int JJTFUNCAO = 3;
  public int JJTRETORNO = 4;
  public int JJTMOSTRAR = 5;
  public int JJTPARA = 6;
  public int JJTSE = 7;
  public int JJTSENAO = 8;
  public int JJTABREPARENTESES = 9;
  public int JJTFECHAPARENTESES = 10;
  public int JJTABRECHAVE = 11;
  public int JJTFECHACHAVE = 12;
  public int JJTVIRGULA = 13;
  public int JJTPONTOVIRGULA = 14;
  public int JJTDELIMITATEXTO = 15;
  public int JJTTIPOID = 16;
  public int JJTTIPOINTEIRO = 17;
  public int JJTTIPOREAL = 18;
  public int JJTTIPOTEXTO = 19;
  public int JJTOPERADORLOGICO = 20;
  public int JJTMENOR = 21;
  public int JJTMAIOR = 22;
  public int JJTMENORIGUAL = 23;
  public int JJTMAIORIGUAL = 24;
  public int JJTDIFERENTE = 25;
  public int JJTIGUAL = 26;
  public int JJTATRIBUIR = 27;
  public int JJTOPERADORMAT = 28;
  public int JJTINCREDECREMENTA = 29;
  public int JJTMAIS = 30;
  public int JJTMENOS = 31;
  public int JJTMULT = 32;
  public int JJTDIVI = 33;
  public int JJTNUMERO = 34;
  public int JJTLETRA = 35;
  public int JJTLETRAMINUSCULA = 36;
  public int JJTLETRAMAIUSCULA = 37;
  public int JJTTEXTO = 38;
  public int JJTID = 39;
  public int JJTCHAMAFUNCAO = 40;
  public int JJTDECLARACAOID = 41;
  public int JJTLISTAID = 42;
  public int JJTREPETICAO = 43;
  public int JJTCONDICIONALSE = 44;
  public int JJTCONDICIONALSENAO = 45;
  public int JJTEXPRESSAO = 46;
  public int JJTIMPRIMIR = 47;
  public int JJTRETORNOFUNCAO = 48;
  public int JJTINICIAID = 49;
  public int JJTCRIAFUNCAO = 50;
  public int JJTCOMANDO = 51;


  public String[] jjtNodeName = {
    "Start",
    "main",
    "ini",
    "funcao",
    "retorno",
    "mostrar",
    "para",
    "se",
    "seNao",
    "abreParenteses",
    "fechaParenteses",
    "abreChave",
    "fechaChave",
    "virgula",
    "pontoVirgula",
    "delimitaTexto",
    "tipoID",
    "tipoInteiro",
    "tipoReal",
    "tipoTexto",
    "operadorLogico",
    "menor",
    "maior",
    "menorIgual",
    "maiorIgual",
    "diferente",
    "igual",
    "atribuir",
    "operadorMat",
    "increDecrementa",
    "mais",
    "menos",
    "mult",
    "divi",
    "numero",
    "letra",
    "letraMinuscula",
    "letraMaiuscula",
    "texto",
    "id",
    "chamaFuncao",
    "declaracaoID",
    "listaID",
    "repeticao",
    "condicionalSe",
    "condicionalSeNao",
    "expressao",
    "imprimir",
    "retornoFuncao",
    "iniciaId",
    "criaFuncao",
    "comando",
  };
}
/* JavaCC - OriginalChecksum=bf7d364f9ca0018131af85f7a8a0a618 (do not edit this line) */
